set_property PACKAGE_PIN G22 [get_ports a]
set_property PACKAGE_PIN F22 [get_ports b]
set_property PACKAGE_PIN T21 [get_ports carry]
set_property PACKAGE_PIN T22 [get_ports sum]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports carry]
set_property IOSTANDARD LVCMOS33 [get_ports sum]
